# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Casey Jones <nahareport@yahoo.com>, 2011
# Hajime Taira <htaira@redhat.com>, 2010-2011
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2009
# Jiří Moskovčák <jmoskovc@redhat.com>, 2011
# Kiyoto Hashida <khashida@redhat.com>, 2009-2011
# Makoto Mizukami <makoto@fedoraporject.org>, 2010
# nnakakit <nnakakit@redhat.com>, 2013
# noriko <noriko@fedoraproject.org>, 2013
# noriko <noriko@fedoraproject.org>, 2012
# noriko <noriko@fedoraproject.org>, 2010
msgid ""
msgstr ""
"Project-Id-Version: gnome-abrt\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-05-02 09:30+0200\n"
"PO-Revision-Date: 2013-05-02 07:30+0000\n"
"Last-Translator: Jakub Filak <jfilak@redhat.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../src/gnome-abrt.desktop.in.h:1 ../src/gnome_abrt/views.py:155
msgid "Automatic Bug Reporting Tool"
msgstr "自動バグ報告ツール（ABRT）"

#: ../src/gnome-abrt.desktop.in.h:2
msgid "View and report application crashes"
msgstr "アプリケーションクラッシュの表示とレポート"

#: ../src/gnome_abrt/dbus_problems.py:55
msgid "Can't add receiver of signal '{0}'on DBus system path '{1}': {2}"
msgstr "DBus システムパス '{1}' にシグナル '{0}' のレシーバーを追加できません : {2}"

#: ../src/gnome_abrt/dbus_problems.py:78
msgid "Can't connect to DBus system bus '{0}' path '{1}': {2}"
msgstr "DBus システムバス '{0}' のパス '{1}' に接続できません: {2}"

#: ../src/gnome_abrt/dbus_problems.py:85
msgid "Can't get interface '{0}' on path '{1}' in bus '{2}': {3}"
msgstr "バス '{2}' 内のパス '{1}' のインターフェース '{0}' を取得できません: {3}"

#: ../src/gnome_abrt/dbus_problems.py:139
msgid "Can't chown problem '{0}' over DBus service: {1!s}"
msgstr "DBus サービス: {1!s} で問題 '{0}' を chown できません"

#: ../src/gnome_abrt/dbus_problems.py:160
msgid "Can't get problem data from DBus service: {0!s}"
msgstr "DBus サービス: {0!s} から問題のデータを取得できません"

#: ../src/gnome_abrt/dbus_problems.py:181
msgid "Can't get list of problems from DBus service: {0!s}"
msgstr "DBus サービス: {0!s} から問題の一覧を取得できません"

#: ../src/gnome_abrt/dbus_problems.py:199
msgid "Can't delete problem over DBus service: {0!s}"
msgstr "DBus サービス: {0!s} で問題を削除できません"

#: ../src/gnome_abrt/dialogs.py:50
msgid "The description of problem is too short"
msgstr ""

#: ../src/gnome_abrt/dialogs.py:51
msgid ""
"In order to get more useful reports we do not accept reports with the "
"description shorter than 10 letters."
msgstr ""

#: ../src/gnome_abrt/dialogs.py:61
msgid "The summary of problem is too short"
msgstr ""

#: ../src/gnome_abrt/dialogs.py:62
msgid ""
"In order to get more useful reports we do not accept reports with the "
"summary shorter than 10 letters."
msgstr ""

#: ../src/gnome_abrt/dialogs.py:88
msgid "Problem description"
msgstr ""

#: ../src/gnome_abrt/dialogs.py:96
msgid "Summary:"
msgstr ""

#: ../src/gnome_abrt/dialogs.py:108
msgid "_Send"
msgstr ""

#. Sets text but text is selected :)
#: ../src/gnome_abrt/dialogs.py:122
msgid "A problem with ABRT"
msgstr ""

#: ../src/gnome_abrt/directory_problems.py:206
msgid ""
"You have probably reached inotify's limit on the number of watches in '{0}'."
" The limit can be increased by proper configuration of inotify. For more "
"details see man inotify(7). This event causes that you will not be notified "
"about changes in problem data happening outside of this application. This "
"event do not affect any other functionality."
msgstr ""

#: ../src/gnome_abrt/directory_problems.py:252
msgid "Can't open directory: '{0}'"
msgstr "ディレクトリを開くことができません: '{0}'"

#: ../src/gnome_abrt/oops.glade.h:1
msgid "Delete"
msgstr "削除"

#: ../src/gnome_abrt/oops.glade.h:2
msgid "Delete selected problems"
msgstr "選択した問題を削除"

#: ../src/gnome_abrt/oops.glade.h:3
msgid "_Report"
msgstr "報告(_R)"

#: ../src/gnome_abrt/oops.glade.h:4
msgid "Submits selected problem"
msgstr "選択した問題をサブミット"

#: ../src/gnome_abrt/oops.glade.h:5
msgid "Analy_ze"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:6
msgid "Open selected problem for analysis"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:7
msgid "_All problems"
msgstr "すべての問題(_A)"

#: ../src/gnome_abrt/oops.glade.h:8
msgid "Show all known problems from all system users"
msgstr "全システムユーザーの既知の問題をすべて表示"

#: ../src/gnome_abrt/oops.glade.h:9
msgid "_Open problem's data directory"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:10
msgid ""
"Opens the selected problem's data directory in the default file system "
"browser"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:11
msgid "_Copy problem's ID to Clipboard"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:12
msgid "Stores the selected problem's ID in Clibpoard"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:13
msgid "Name"
msgstr "名前"

#: ../src/gnome_abrt/oops.glade.h:14
msgid "Version"
msgstr "バージョン"

#: ../src/gnome_abrt/oops.glade.h:15
msgid "Detected"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:16
msgid "Reported"
msgstr "報告済み"

#: ../src/gnome_abrt/oops.glade.h:17
msgid "No problems detected!"
msgstr ""

#: ../src/gnome_abrt/oops.glade.h:18
msgid "App"
msgstr "アプリ"

#: ../src/gnome_abrt/oops.glade.h:19
msgid "Date"
msgstr "日付"

#: ../src/gnome_abrt/problems.py:174
msgid "Can't delete problem '{0}': '{1}'"
msgstr "問題 '{0}' を削除できません: '{1}'"

#: ../src/gnome_abrt/problems.py:345
msgid "Not found in cache but deleted: {0}"
msgstr "キャッシュ内では見つかりませんが削除されました: {0}"

#: ../src/gnome_abrt/problems.py:364
msgid "Source failed on processing of '{0}': {1}"
msgstr "ソースが '{0}' の処理に失敗しました: {1}"

#: ../src/gnome_abrt/tools.py:33
msgid "Future"
msgstr "今後"

#: ../src/gnome_abrt/tools.py:40
msgid "Yesterday"
msgstr "昨日"

#: ../src/gnome_abrt/tools.py:49
msgid "week"
msgstr "週"

#: ../src/gnome_abrt/tools.py:52
msgid "month"
msgstr "月"

#: ../src/gnome_abrt/tools.py:55
msgid "year"
msgstr "年"

#: ../src/gnome_abrt/tools.py:58
msgid "Last {0!s}"
msgstr "最終 {0!s}"

#: ../src/gnome_abrt/tools.py:60
msgid "{0:d} {1!s}s ago"
msgstr "{0:d} {1!s} 前"

#: ../src/gnome_abrt/views.py:83 ../src/gnome_abrt/views.py:368
#: ../src/gnome_abrt/views.py:370
msgid "N/A"
msgstr "該当なし"

#: ../src/gnome_abrt/views.py:370
msgid " crashed"
msgstr "クラッシュ"

#: ../src/gnome_abrt/views.py:383
msgid "yes"
msgstr "はい"

#: ../src/gnome_abrt/views.py:386
msgid "no"
msgstr "いいえ"

#: ../src/gnome_abrt/views.py:394
msgid ""
"This problem hasn't been reported to <i>Bugzilla</i> yet. Our developers may need more information to fix the problem.\n"
"Please consider <b>reporting it</b> - you may help them. Thank you."
msgstr ""
